# Generated by Django 2.1.5 on 2019-04-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_projectstatus_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
    ]
