# Generated by Django 2.1.5 on 2019-04-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_auto_20190414_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
